CREATE DATABASE QL_KHACHSAN
go
USE QL_KHACHSAN
go
CREATE TABLE NHANVIEN
(
 MANV VARCHAR(11) NOT NULL,
 TENNV VARCHAR(50) NOT NULL,
 CHUCVU VARCHAR(50),
 LUONGNV float,
 NGAYSINH DATE,
 GIOITINH CHAR(3),
 CHUTHICH VARCHAR(50),
 
 PRIMARY KEY (MANV)
 
 );
 go
 CREATE TABLE DICHVU
(
 MADV VARCHAR(11) NOT NULL,
 TENDV VARCHAR(50) NOT NULL,
 GIADV float,
 
 PRIMARY KEY (MADV)
 
 );
 go
 CREATE TABLE PHONG
(
 MAPHONG VARCHAR(11) NOT NULL,
 TENPHONG VARCHAR(50) NOT NULL,
 LOAIPHONG VARCHAR(20) NOT NULL,
 GIAPHONG float,
 CHUTHICH VARCHAR(50),
 TINHTRANG VARCHAR(50),
 MANV VARCHAR(11),
 MADV VARCHAR(11),
 
 PRIMARY KEY (MAPHONG),
 CONSTRAINT fk_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
 CONSTRAINT fk_DICHVU FOREIGN KEY (MADV) REFERENCES DICHVU(MADV)
 
);

go
CREATE TABLE KHACHHANG
(
 MAKH VARCHAR(11) NOT NULL,
 TENKH VARCHAR(50) NOT NULL,
 CMND VARCHAR(20) NOT NULL,
 QUOCTICH VARCHAR(50),
 GIOITINH CHAR(3),
 TUOI INT,
 SDT VARCHAR(20),
 MAPHONG VARCHAR(11),
 
 PRIMARY KEY (MAKH),
 CONSTRAINT fk_PHONG FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG)
 
 );
 go
 CREATE TABLE HOADON
(
 MAHD VARCHAR(11) NOT NULL,
 MANV VARCHAR(11),
 MAPHONG VARCHAR(11),
 NGAY DATE,
 GIAHD float,
 PRIMARY KEY (MAHD)

 );
